name: CI/CD Pipeline - InovaGAB

on:
  push:
    branches: [ "main", "master", "staging" ]
  pull_request:
    branches: [ "main", "master", "staging" ]

jobs:
  build-and-test:
    name: 1. Build e Testes (Java Maven)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17 / JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar e Executar Testes
        run: mvn clean package -DskipTests=false

  docker-build:
    name: 2. Build da Imagem Docker
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Testar Build da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: false
          tags: inovagab-backend:latest

<<<<<<< Updated upstream
  deploy-production:
    name: 3. Deploy em Produção
=======
  deploy-staging:
    name: 3. Deploy em Staging
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy no Render
        run: curl -fsS -X POST "${{ secrets.RENDER_STAGING_DEPLOY_HOOK }}"

  deploy-production:
    name: 4. Deploy em Produção
>>>>>>> Stashed changes
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy no Render
<<<<<<< Updated upstream
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
=======
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
>>>>>>> Stashed changes
