name: CI/CD Pipeline - InovaGAB

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    name: 1. Build e Testes (Java Maven)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17 / JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar e Executar Testes
        run: mvn clean package -DskipTests=false

  docker-build:
    name: 2. Build da Imagem Docker
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Testar Build da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: false
          tags: inovagab-backend:latest

    deploy-production:
        name: 3. Deploy em Produção
        needs: docker-build
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
          - name: Deploy no Render
            run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
